name: Trigger Lovable Sync Demo

on:
  push:
    branches:
      - main

jobs:
  trigger-sync:
    runs-on: ubuntu-latest
    steps:
      - name: Call Lovable Sync Endpoint
        env:
          SYNC_URL: ${{ secrets.LOVABLE_SYNC_URL }} # e.g. https://your-server.example.com/api/savePlayer
          SYNC_KEY: ${{ secrets.LOVABLE_SYNC_KEY }}
        run: |
          echo "Triggering Lovable sync..."
          curl -X POST "$SYNC_URL" \
            -H "Content-Type: application/json" \
            -H "Authorization: Bearer $SYNC_KEY" \
            -d '{"note":"Triggered from GitHub Action","time":"'"$(date -u)"'"}'
